# Generated by Django 2.2.2 on 2019-09-17 09:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=150)),
                ('trwalk', models.IntegerField()),
                ('Dtwalk', models.IntegerField()),
                ('trclassic', models.IntegerField()),
                ('Dtclassic', models.IntegerField()),
                ('trelectric', models.IntegerField()),
                ('Dtelectric', models.IntegerField()),
                ('totalMilage', models.IntegerField()),
                ('totalweight', models.IntegerField()),
                ('phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Udetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('dstrtype', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('movingtime', models.CharField(max_length=150)),
                ('additionalbox', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.Muser')),
            ],
        ),
    ]
