# Generated by Django 2.2.2 on 2019-09-23 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20190919_1204'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muser',
            name='timestamp',
        ),
        migrations.RemoveField(
            model_name='udetails',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='muser',
            name='fromm',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='muser',
            name='too',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='udetails',
            name='fromm',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='udetails',
            name='too',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
