# Generated by Django 2.2.2 on 2019-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20190923_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muser',
            name='Dtclassic',
            field=models.IntegerField(help_text='Distributed by classic will be in KG'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='Dtelectric',
            field=models.IntegerField(help_text='Distributed by electric will be in KG'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='Dtwalk',
            field=models.IntegerField(help_text='Distributed by walk will be in KG'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='phone',
            field=models.CharField(help_text='phone will be in phone number format', max_length=20),
        ),
        migrations.AlterField(
            model_name='muser',
            name='totalMilage',
            field=models.IntegerField(help_text='Total Milage  will be in KM'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='totalweight',
            field=models.IntegerField(help_text='Total weight  will be in KG'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='trclassic',
            field=models.IntegerField(help_text='travel by classic will be in KM'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='trelectric',
            field=models.IntegerField(help_text='travel by electric will be in KM'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='trwalk',
            field=models.IntegerField(help_text='travel by walk will be in KM'),
        ),
        migrations.AlterField(
            model_name='muser',
            name='user',
            field=models.CharField(help_text='User will be in name', max_length=150),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='additionalbox',
            field=models.IntegerField(help_text='Additionl box will be in Number'),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='dstrtype',
            field=models.CharField(choices=[('ELECTRIC BIKE', 'Electric Bike'), ('CLASSIC BIKE', 'Clasic Bike'), ('WALK', 'Walk')], help_text='Select from box', max_length=150),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='kgtransported',
            field=models.IntegerField(default=14, help_text='Kg Transportd will be in Kg'),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='milage',
            field=models.IntegerField(help_text='Milage will be in Km'),
        ),
        migrations.AlterField(
            model_name='udetails',
            name='movingtime',
            field=models.FloatField(help_text='moving time will be in decimal'),
        ),
    ]
