# Generated by Django 2.2.5 on 2019-10-07 09:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bikes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('too', models.DateField(default=datetime.datetime.now)),
                ('fromm', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('milage', models.IntegerField(default=10, help_text='Milage Will be in Km/hr')),
                ('movingtime', models.FloatField(default=10, help_text='Milage Will be in 5.30hr')),
                ('averagespeed', models.IntegerField(default=10, help_text='Average Speed Will be in km/hr')),
                ('letteritems', models.IntegerField(default=10, help_text='This field Will be in digit')),
                ('shipweight', models.IntegerField(default=10, help_text='This field Will be in kgs')),
                ('package', models.IntegerField(default=10, help_text='This field Will be in digit')),
                ('kgtrasported', models.IntegerField(default=10, help_text='Kg Transported will be in Kg')),
                ('co2', models.IntegerField(default=10, help_text='Co2 will be in mg ')),
                ('additionalbox', models.IntegerField(default=10, help_text='Additional Boxes will be in Number ')),
                ('nouser', models.IntegerField(default=10, help_text='No Of User will be in integer')),
                ('mode', models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('electric-bike', 'electric-bike')], help_text='Mode of transport', max_length=64, null=True)),
                ('too', models.DateField(default=datetime.datetime.now)),
                ('fromm', models.DateField(default=datetime.datetime.now)),
                ('electric_bike', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='bikes.ElectricBike')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='deliveries.User')),
            ],
            options={
                'ordering': ('timestamp',),
            },
        ),
    ]
