# Generated by Django 2.2.2 on 2019-10-07 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery',
            name='addresses',
            field=models.IntegerField(default=1, help_text='No Of address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='letters_number',
            field=models.IntegerField(default=1, help_text='No Of address'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='letters_weight',
            field=models.FloatField(default=10, help_text='Kg Transported will be in Kg'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='packaged_weight',
            field=models.FloatField(default=10, help_text='Kg Transported will be in Kg'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='packages_number',
            field=models.IntegerField(default=1, help_text='No Of address'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(default='iamrra', on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='deliveries.User'),
        ),
    ]
