# Generated by Django 2.2.5 on 2019-09-19 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0002_auto_20190919_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='mode',
            field=models.CharField(blank=True, choices=[('foot', 'foot'), ('bike', 'bike'), ('electric-bike', 'electric-bike')], help_text='Mode of transport', max_length=64, null=True),
        ),
    ]
