# Generated by Django 2.2.2 on 2019-09-26 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_auto_20190919_1023'),
        ('electric', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delivery',
            name='electric_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electric.ElectricBike'),
        ),
    ]
