# Generated by Django 2.2.2 on 2019-10-04 14:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('deliveries', '0003_auto_20190919_1023'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('too', models.DateField(default=datetime.datetime.now)),
                ('fromm', models.DateField(default=datetime.datetime.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
            },
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='addresses',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='letters_number',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='letters_weight',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='packaged_weight',
        ),
        migrations.RemoveField(
            model_name='delivery',
            name='packages_number',
        ),
        migrations.AddField(
            model_name='delivery',
            name='additionalbox',
            field=models.IntegerField(default=10, help_text='Additional Boxes will be in Number '),
        ),
        migrations.AddField(
            model_name='delivery',
            name='averagespeed',
            field=models.IntegerField(default=10, help_text='Average Speed Will be in km/hr'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='co2',
            field=models.IntegerField(default=10, help_text='Co2 will be in mg '),
        ),
        migrations.AddField(
            model_name='delivery',
            name='fromm',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='delivery',
            name='kgtrasported',
            field=models.IntegerField(default=10, help_text='Kg Transported will be in Kg'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='letteritems',
            field=models.IntegerField(default=10, help_text='This field Will be in digit'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='milage',
            field=models.IntegerField(default=10, help_text='Milage Will be in Km/hr'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='movingtime',
            field=models.FloatField(default=10, help_text='Milage Will be in 5.30hr'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='nouser',
            field=models.IntegerField(default=10, help_text='No Of User will be in integer'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='package',
            field=models.IntegerField(default=10, help_text='This field Will be in digit'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='shipweight',
            field=models.IntegerField(default=10, help_text='This field Will be in kgs'),
        ),
        migrations.AddField(
            model_name='delivery',
            name='too',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='electric_bike',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='results', to='bikes.ElectricBike'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail', to='deliveries.User'),
        ),
    ]
