# Generated by Django 2.2.5 on 2019-09-09 13:28

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0002_databatch_uuid'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='databatch',
            unique_together={('user', 'uuid')},
        ),
    ]
