# Generated by Django 2.2.5 on 2019-09-19 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20190909_1328'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='databatch',
            options={'ordering': ('received_at',)},
        ),
    ]
