# Generated by Django 2.2.2 on 2019-09-23 13:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clasic', '0004_auto_20190923_0949'),
        ('user', '0004_auto_20190923_0949'),
        ('electric', '0015_auto_20190923_1310'),
        ('walk', '0004_auto_20190923_0949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Electric  Bike Report', max_length=150)),
                ('too', models.DateField(default=datetime.datetime.now)),
                ('fromm', models.DateField(default=datetime.datetime.now)),
                ('classic', models.ForeignKey(help_text='Classic Bike id', on_delete=django.db.models.deletion.CASCADE, related_name='classic', to='clasic.ClassicBike')),
                ('electric', models.ForeignKey(help_text='Electric Bike id', on_delete=django.db.models.deletion.CASCADE, related_name='electric', to='electric.ElectricBike')),
                ('user', models.ForeignKey(help_text='user from Username id', on_delete=django.db.models.deletion.CASCADE, related_name='muser', to='user.Muser')),
                ('walk', models.ForeignKey(help_text='Walk id', on_delete=django.db.models.deletion.CASCADE, related_name='walk', to='walk.Walk')),
            ],
        ),
    ]
