# Generated by Django 2.2.5 on 2019-09-19 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='electricbike',
            options={'ordering': ('label',)},
        ),
        migrations.RemoveField(
            model_name='electricbike',
            name='identifier',
        ),
        migrations.AddField(
            model_name='electricbike',
            name='label',
            field=models.CharField(default='', help_text='Textual bike identifier', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
