# Generated by Django 2.2.2 on 2019-09-27 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bikes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electricbike',
            name='fromm',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='electricbike',
            name='too',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
