# Generated by Django 2.2.5 on 2019-10-07 09:33

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicBike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bikeid', models.CharField(help_text='Bike id will be in String', max_length=100)),
                ('milage', models.IntegerField(help_text='Milage will be in Km')),
                ('movingtime', models.FloatField(help_text='moving time will be in decimal')),
                ('letteritems', models.IntegerField(default=10, help_text='This field Will be in digit')),
                ('shipweight', models.IntegerField(default=10, help_text='This field Will be in kgs')),
                ('package', models.IntegerField(default=10, help_text='This field Will be in digit')),
                ('averagespeed', models.IntegerField(help_text='Average Speed will be in Km')),
                ('kgtrasported', models.IntegerField(help_text='Kg Transportd will be in Kg')),
                ('co2', models.IntegerField(help_text='CO2 saved, in mg')),
                ('additionalbox', models.IntegerField(help_text='Additionl box will be in Number')),
                ('too', models.DateField(default=datetime.datetime.now)),
                ('fromm', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Cdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField(help_text='Milage will be in Km')),
                ('movingtime', models.FloatField(help_text='moving time will be in decimal')),
                ('letteritems', models.IntegerField(default=10, help_text='This field Will be in digit')),
                ('shipweight', models.IntegerField(default=10, help_text='This field Will be in kgs')),
                ('package', models.IntegerField(default=10, help_text='This field Will be in digit')),
                ('averagespeed', models.IntegerField(help_text='Average Speed will be in Km')),
                ('kgtrasported', models.IntegerField(help_text='Kg Transportd will be in Kg')),
                ('additionalbox', models.IntegerField(help_text='Additionl box will be in Number')),
                ('too', models.DateField(default=datetime.datetime.now)),
                ('fromm', models.DateField(default=datetime.datetime.now)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='clasic.ClassicBike')),
            ],
        ),
    ]
