# Generated by Django 2.2.2 on 2019-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clasic', '0008_auto_20190925_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cdetails',
            name='additionalbox',
            field=models.IntegerField(help_text='Additionl box will be in Number'),
        ),
        migrations.AlterField(
            model_name='cdetails',
            name='averagespeed',
            field=models.IntegerField(help_text='Average Speed will be in Km'),
        ),
        migrations.AlterField(
            model_name='cdetails',
            name='kgtrasported',
            field=models.IntegerField(help_text='Kg Transportd will be in Kg'),
        ),
        migrations.AlterField(
            model_name='cdetails',
            name='milage',
            field=models.IntegerField(help_text='Milage will be in Km'),
        ),
        migrations.AlterField(
            model_name='cdetails',
            name='movingtime',
            field=models.FloatField(help_text='moving time will be in decimal'),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='additionalbox',
            field=models.IntegerField(help_text='Additionl box will be in Number'),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='averagespeed',
            field=models.IntegerField(help_text='Average Speed will be in Km'),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='bikeid',
            field=models.CharField(help_text='Bike id will be in String', max_length=100),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='co2',
            field=models.IntegerField(help_text='CO2 saved, in mg'),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='kgtrasported',
            field=models.IntegerField(help_text='Kg Transportd will be in Kg'),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='milage',
            field=models.IntegerField(help_text='Milage will be in Km'),
        ),
        migrations.AlterField(
            model_name='classicbike',
            name='movingtime',
            field=models.FloatField(help_text='moving time will be in decimal'),
        ),
    ]
