# Generated by Django 2.2.2 on 2019-09-17 10:44

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Walk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150)),
                ('milage', models.IntegerField()),
                ('movingtime', models.CharField(max_length=150)),
                ('kgtransported', models.IntegerField()),
                ('additionalbox', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wdetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('milage', models.IntegerField()),
                ('movingtime', models.CharField(max_length=150)),
                ('kgtransported', models.IntegerField()),
                ('additionalbox', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='walk.Walk')),
            ],
        ),
    ]
