# Generated by Django 2.2.2 on 2019-09-19 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0002_auto_20190919_1204'),
    ]

    operations = [
        migrations.AddField(
            model_name='wdetails',
            name='movingtime',
            field=models.CharField(default='3h 13min', max_length=150),
        ),
        migrations.AlterField(
            model_name='walk',
            name='movingtime',
            field=models.CharField(default='3h 13min', max_length=150),
        ),
    ]
