# Generated by Django 2.2.2 on 2019-09-25 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0004_auto_20190923_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='walk',
            name='letteritems',
            field=models.IntegerField(default=10, help_text='This field Will be in digit'),
        ),
        migrations.AddField(
            model_name='walk',
            name='package',
            field=models.IntegerField(default=10, help_text='This field Will be in digit'),
        ),
        migrations.AddField(
            model_name='walk',
            name='shipweight',
            field=models.IntegerField(default=10, help_text='This field Will be in kgs'),
        ),
        migrations.AddField(
            model_name='wdetails',
            name='letteritems',
            field=models.IntegerField(default=10, help_text='This field Will be in digit'),
        ),
        migrations.AddField(
            model_name='wdetails',
            name='package',
            field=models.IntegerField(default=10, help_text='This field Will be in digit'),
        ),
        migrations.AddField(
            model_name='wdetails',
            name='shipweight',
            field=models.IntegerField(default=10, help_text='This field Will be in kgs'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='movingtime',
            field=models.FloatField(default=5.3, help_text='This Field will be in decimal 5.30'),
        ),
        migrations.AlterField(
            model_name='wdetails',
            name='movingtime',
            field=models.FloatField(default=5.3, help_text='This Field will be in decimal 5.30'),
        ),
    ]
