# Generated by Django 2.2.2 on 2019-09-25 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0007_auto_20190925_1232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='movingtime',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='wdetails',
            name='movingtime',
            field=models.FloatField(default=10),
        ),
    ]
