# Generated by Django 2.2.2 on 2019-10-04 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0008_auto_20190925_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wdetails',
            name='user',
        ),
        migrations.DeleteModel(
            name='Walk',
        ),
        migrations.DeleteModel(
            name='Wdetails',
        ),
    ]
