# Generated by Django 2.2.2 on 2019-09-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk', '0008_auto_20190925_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='additionalbox',
            field=models.IntegerField(help_text='Average Speed will be in Km'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='kgtransported',
            field=models.IntegerField(help_text='Kg Transportd will be in Kg'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='milage',
            field=models.IntegerField(help_text='Milage will be in Km'),
        ),
        migrations.AlterField(
            model_name='walk',
            name='movingtime',
            field=models.FloatField(help_text='moving time will be in decimal'),
        ),
        migrations.AlterField(
            model_name='wdetails',
            name='additionalbox',
            field=models.IntegerField(help_text='Average Speed will be in Km'),
        ),
        migrations.AlterField(
            model_name='wdetails',
            name='kgtransported',
            field=models.IntegerField(help_text='Kg Transportd will be in Kg'),
        ),
        migrations.AlterField(
            model_name='wdetails',
            name='milage',
            field=models.IntegerField(help_text='Milage will be in Km'),
        ),
        migrations.AlterField(
            model_name='wdetails',
            name='movingtime',
            field=models.FloatField(help_text='moving time will be in decimal'),
        ),
    ]
