# Generated by Django 2.2.2 on 2019-09-16 11:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectricBike',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bikeid', models.CharField(max_length=100)),
                ('milage', models.IntegerField()),
                ('movingtime', models.CharField(max_length=150)),
                ('averagespeed', models.IntegerField()),
                ('kgtrasported', models.IntegerField()),
                ('co2', models.IntegerField()),
                ('additionalbox', models.IntegerField()),
                ('nouser', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Edetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('user', models.CharField(max_length=150)),
                ('milage', models.IntegerField()),
                ('movingtime', models.CharField(max_length=150)),
                ('averagespeed', models.IntegerField()),
                ('kgtrasported', models.IntegerField()),
                ('additionalbox', models.IntegerField()),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='electric.ElectricBike')),
            ],
        ),
    ]
