# Generated by Django 2.2.2 on 2019-09-23 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0004_auto_20190919_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edetails',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='timestamp',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
