# Generated by Django 2.2.2 on 2019-09-23 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0005_auto_20190923_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edetails',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
