# Generated by Django 2.2.2 on 2019-09-23 08:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0006_auto_20190923_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbike',
            name='timestamp',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
