# Generated by Django 2.2.2 on 2019-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0007_auto_20190923_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbike',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
