# Generated by Django 2.2.2 on 2019-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0008_auto_20190923_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricbike',
            old_name='timestamp',
            new_name='frm',
        ),
        migrations.AddField(
            model_name='electricbike',
            name='to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
