# Generated by Django 2.2.2 on 2019-09-23 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0011_auto_20190923_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbike',
            name='frm',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='to',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
