# Generated by Django 2.2.2 on 2019-09-23 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0013_electricbike_dd'),
    ]

    operations = [
        migrations.RenameField(
            model_name='electricbike',
            old_name='dd',
            new_name='fromm',
        ),
        migrations.RemoveField(
            model_name='edetails',
            name='frm',
        ),
        migrations.RemoveField(
            model_name='edetails',
            name='to',
        ),
        migrations.RemoveField(
            model_name='electricbike',
            name='frm',
        ),
        migrations.RemoveField(
            model_name='electricbike',
            name='to',
        ),
        migrations.AddField(
            model_name='edetails',
            name='fromm',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='edetails',
            name='too',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='electricbike',
            name='too',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
