# Generated by Django 2.2.2 on 2019-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0014_auto_20190923_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electricbike',
            name='additionalbox',
            field=models.IntegerField(help_text='Additional Boxes will be in Number '),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='averagespeed',
            field=models.IntegerField(help_text='Average Speed Will be in km/hr'),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='bikeid',
            field=models.CharField(help_text='Bike id will be String', max_length=100),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='co2',
            field=models.IntegerField(help_text='Co2 will be in mg '),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='kgtrasported',
            field=models.IntegerField(help_text='Kg Transported will be in Kg'),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='milage',
            field=models.IntegerField(help_text='Milage Will be in Km/hr'),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='movingtime',
            field=models.CharField(default='3h 13min', help_text='Moving Time will be in like 3h 13min', max_length=150),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='nouser',
            field=models.IntegerField(help_text='No Of User will be in integer'),
        ),
    ]
