# Generated by Django 2.2.2 on 2019-09-25 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0016_auto_20190925_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edetails',
            name='movingtime',
            field=models.FloatField(default=5.3, help_text='This Field will be in decimal 5.30'),
        ),
    ]
