# Generated by Django 2.2.2 on 2019-09-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electric', '0017_auto_20190925_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edetails',
            name='movingtime',
            field=models.FloatField(default=5, help_text='This Field will be in decimal 5.30'),
        ),
        migrations.AlterField(
            model_name='electricbike',
            name='movingtime',
            field=models.FloatField(default=5, help_text='This Field will be in decimal 5.30'),
        ),
    ]
